### ISSUE TITLE
Differentiate license of IEEE Std 802, IEEE Std 2030, and IEEE 1003 (POSIX)

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-ieee#21]
Q: 2021 Style Manual 12.3.5 says that the first instance of an IEEE citation needs to be followed by ® or ™, but does not indicate when to apply which. In copyright the ® is applied when a trademark is registered, and ™ when it is not. Is there a list of IEEE trademarks that are registered (®), vs those that are not (™)?

Answer from IEEE:
> Virtually all IEEE standards are trademarked "TM" with very rare exceptions [IEEE Std 802, IEEE Std 2030, and IEEE 1003 (POSIX) get the (R) trademark]

The following standards, when cited in IEEE, need ® rather than ™. :
* IEEE Std 802
* IEEE Std 2030
* IEEE 1003 (POSIX)

To indicate that, I request that they be given this element in bibliographic data:

```xml
<license>registered-trademark</license>
```

**Comment by ronaldtse** [comment]
Instead of license, the ® element indicates that the following phrases are trademarked by IEEE:

* "802"
* "IEEE 2030"
* "POSIX"

The trademarks are:
* "802" (so "IEEE 802" and "IEEE Std 802" both show (R) after 802)

<img width="1299" alt="Screenshot 2022-06-30 at 6 29 55 PM" src="https://user-images.githubusercontent.com/11865/176643390-36d29a3d-6577-48a7-9360-e10b2ee25398.png">

* "IEEE 2030"
<img width="1306" alt="Screenshot 2022-06-30 at 6 31 45 PM" src="https://user-images.githubusercontent.com/11865/176643743-ebfa882a-ae1b-4629-87d7-a27958d6e77b.png">
<img width="1312" alt="Screenshot 2022-06-30 at 6 32 48 PM" src="https://user-images.githubusercontent.com/11865/176643934-c0a6a199-25b5-4b7e-b9bc-60147d249fdc.png">

* "POSIX"
But POSIX is "DEAD"!
<img width="1312" alt="Screenshot 2022-06-30 at 6 35 20 PM" src="https://user-images.githubusercontent.com/11865/176644546-bb868161-1811-4297-b269-17626fe05379.png">

**Comment by opoudjis** [comment]
The rule is that the ®/™ is inserted after first mention only, and Metanorma is already doing that.

I anticipated that objection, but was hoping we could be pragmatic. Since we clearly cannot, alternative docidentifier, `<docidentifier type="IEEE" scope="trademark">`, or `<docidentifier type="IEEE-trademark">`

**Comment by ronaldtse** [comment]
@opoudjis the solution does not feel "clean" to me because Metanorma should not be the location where the "trademark" information is retained. Do you have another suggestion?

**Comment by opoudjis** [comment]
@ronaldtse: 

> The rule is that the ®/™ is inserted after first mention only

That is not bibliography, that is rendering. Rendering information does not belong in Relaton, that is where the semantics comes from. Despite that not being my preference, I have conceded to you having Relaton have two versions of the identifier, one trademarked and one not, and having Metarnorma pick which one it uses according to context. 

My suggestion is that you stop constantly second guessing me, and let me do my job.

**Comment by andrew2net** [comment]
Implemented, but it seems "IEEE 1003 (POSIX)" doesn't match any identifiers, so only identifiers matched `IEEE Std 802`, `IEEE 802`, `IEEE Std 2030`, or `IEEE 2030` are set as `trademark`.

**Comment by opoudjis** [comment]
First, for any document not matching those standard numbers, I require:

`<docidentifier type="IEEE" scope="trademark">...</docidentifier>`

with a ™ after the document number, but before any year. So for example, `relaton fetch "IEEE  1619-2007"` should return

````
  <docidentifier type="IEEE" primary="true">IEEE 1619-2007</docidentifier>
  <docidentifier type="IEEE" primary="true" scope="trademark">IEEE 1619™-2007</docidentifier>
````

Second, I need the same for 802, 2030, only using ® instead of ™.  So `bundle exec relaton fetch "IEEE 2030"` should return not

````
  <docidentifier type="IEEE" scope="trademark" primary="true">IEEE 2030-2011</docidentifier>
````

but

````
  <docidentifier type="IEEE" primary="true">IEEE 2030-2011</docidentifier>
  <docidentifier type="IEEE" primary="true" scope="trademark">IEEE 2030®-2011</docidentifier>
````

**Comment by andrew2net** [comment]
@ronaldtse Do we need to update identifiers in the `relaton-data-ieee` repo?

**Comment by ronaldtse** [comment]
Yes we should make the trademarked doc identifier available in the dataset as well.
